### ISSUE TITLE
Can't find Module Error

### ISSUE THREAD

**Issue by 40182335** [jxcore/jxcore-cordova#100]
Hi,

the provided example works perfectly fine on my android device.
But I can't require different node modules e.h.
I install serialport
 /www/jxcore> jx install serialport --autoremove "*.gz" 
requiring it results in an error: "MODULE_NOT_FOUND"
Other modules give me the same result.
 (json-nice from the sample folder works btw)

I'm on win7x64

**Comment by ktrzeciaknubisa** [comment]
Are you sure, that serialport (and other modules you have tried) got installed under www/jxcore/node_modules? I'm asking in case you had node_modules in one of parent directories - installed packages could end up in there.

I was able to `require('serialport')` on android without "MODULE_NOT_FOUND", however I got other error (which is expected since that is a native module):

``` bash
Cannot find module '/data/........./serialport.node'
```

**Comment by 40182335** [comment]
Ah yes, the module did end up in a parent directories node_modules folder. Thank you!
