### ISSUE TITLE
The README doesn't seem quite right

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore-cordova#15]
I had to make the following changes to get my jxcore-cordova hello world app running that weren't in the instructions:
1. In index.html I had to copy in the following to get a correct path to jxcore.js, not as listed:

``` xml
<script type="text/javascript" charset="utf-8" src="plugins\io.jxcore.node\www\jxcore.js"></script>
```
1. The index.html is under sample/www not sample as stated in the readme
2. The current sample uses inline script. It would appear (I'm really not an expert) that Chrome (aka Android's webview on newer releases, I'm using SDK 21) will not support inline scripts, period. For security reasons it requires the script to be defined in a separate js file. So I took the Javascript from the sample file and pulled it out into a separate file called jxcoredemo.js that I then called from inside of index.html. That worked.
3. The sample file implies that the script tag should be in the head. But in the Android sample shipped with Cordova they put the tags in the body. They also explicitly include a call to js/index.js, but that may just be part of their sample.
4. The current readme suggests installing the JXCORE-CORDOVA project underneath the Cordova project. That seems kind of mean. It's going to make a real mess out of version control. Personally I installed it in a sibling directory and then used cordova plugin add from there. But that's just me.
5. The good news is that once I make the fixes above the sample does run successfully! The bad news is that I'm still getting some odd errors but they aren't show stoppers. But it would still be good to know why:

```
05-14 16:26:33.531  11564-11598/org.thaliproject.postcardapp W/PluginManager﹕ THREAD WARNING: exec() call to JXcore.Evaluate blocked the main thread for 641ms. Plugin should use CordovaInterface.getThreadPool().
05-14 16:26:33.541  11564-11598/org.thaliproject.postcardapp D/dalvikvm﹕ GC_FOR_ALLOC freed 442K, 11% free 9354K/10416K, paused 14ms, total 14ms
05-14 16:26:34.572      886-886/? I/ConfigService﹕ onDestroy
05-14 16:26:36.905  11564-11564/org.thaliproject.postcardapp D/SystemWebChromeClient﹕ file:///android_asset/www/cordova.js: Line 1185 : deviceready has not fired after 5 seconds.
05-14 16:26:36.905  11564-11564/org.thaliproject.postcardapp I/chromium﹕ [INFO:CONSOLE(1185)] "deviceready has not fired after 5 seconds.", source: file:///android_asset/www/cordova.js (1185)
05-14 16:26:36.905  11564-11564/org.thaliproject.postcardapp D/SystemWebChromeClient﹕ file:///android_asset/www/cordova.js: Line 1178 : Channel not fired: onJXcoreReady
05-14 16:26:36.905  11564-11564/org.thaliproject.postcardapp I/chromium﹕ [INFO:CONSOLE(1178)] "Channel not fired: onJXcoreReady", source: file:///android_asset/www/cordova.js (1178)
```

That first warning is kind of scary.

I'm also not clear why deviceReady and onJXcoreReady aren't firing.

**Comment by obastemur** [comment]
Yes, inline script is not the best but people are already suffering from using the scripts from index.html under samples/www , what could be the result if I make it even harder to find. That shows just the basics. 

THREAD WARNING is something kind of a temporary design choice. After whole day of fighting with the ARM thread scheduler problem (the one Jukka stumbled into on his device), now were are even closer to have a separate thread on Android. Unfortunately this is not an (easy) option for iOS. iOS doesn't allow a subthread creating it's sub thread. In other words, if we initialize JXcore under a subthread, there is no living space for libUV IO threads. There is a trick we can work on. Actually the current ios interface design already covers async execution of jxcore but it will be the best dealing with this after stabilizing the other parts.

I'm no longer searching an answer for device_ready thing. 

ping @ktrzeciaknubisa / @plika  (README fixes)

**Comment by deefactorial** [comment]
The device ready thing can be fixed by redirecting. Index.html to main.html right away. 
window.location=main.html;
Then put all your logic in main.html
It happens when there is too many scripts loading. Its a cordova thing.

The blocking the main thread warning is when you run your code on the ui thread. The android way is to start a seperate thread, but it will work just fine.
Is node js running on a background service? Meaning if I switch from my app to chrome and go to localhost:3030 will I reach the sever running in node?

**Comment by ktrzeciaknubisa** [comment]
@yaronyg 

> In index.html I had to copy in the following to get a correct path to jxcore.js, not as listed: 
> 
> ``` html
> <script type="text/javascript" charset="utf-8" src="plugins\io.jxcore.node\www\jxcore.js">
> </script>
> ```

Basically you're right, `jxcore.js` stays under `./plugins/io.jxcore.node/www`. But providing a full path is not necessary from what I saw. I guess it's due to definition present in `cordova_plugins.js` file. I've checked this by adding an `alert("hello")` to the `jxcore.js` file and it worked even with the original src value:  

``` html
<script type="text/javascript" charset="utf-8" src="jxcore.js"></script>
```

**Comment by yaronyg** [comment]
@ktrzeciaknubisa The code wouldn't work for me unless I put in that full path. Are y'all testing against the latest Android SDK?

**Comment by deefactorial** [comment]
I'm using 
Android SDK 24.1.2
Cordova 4.3.0 
and it works fine for me to have script src="jxcore.js"

**Comment by ktrzeciaknubisa** [comment]
@yaronyg Yeap, I'm updating it regularly, even today. What about `cordova --version`? 

Android SDK Tools 24.2
Cordova 4.3.0

**Comment by yaronyg** [comment]
I'm running cordova 5.0.0 with Android 22

**Comment by obastemur** [comment]
Just added cordova 5.0 support. Thanks for details!

**Comment by Mithgol** [comment]
@yaronyg

> The current sample uses inline script. It would appear (I'm really not an expert) that Chrome (aka Android's webview on newer releases, I'm using SDK 21) will not support inline scripts, period. For security reasons it requires the script to be defined in a separate js file. So I took the Javascript from the sample file and pulled it out into a separate file called jxcoredemo.js that I then called from inside of index.html. That worked.

There was a rule in the sample's content security policy that prohibited inline scripts. Fixed in 23681d7b4ff117d2840f4fb5177deb1d361658aa.

> The sample file implies that the script tag should be in the head. But in the Android sample shipped with Cordova they put the tags in the body. They also explicitly include a call to js/index.js, but that may just be part of their sample.

Putting `<script>` before `</body>` allows a web page to be displayed faster (before its scripts are downloaded), though there's a tradeoff: the page does not become interactive before the moment when scripts are downloaded.

However, scripts of a Cordova-based applications are present on the device (they have zero “download time”) and thus we can put our `<script>` tags anywhere.

> The current readme suggests installing the JXCORE-CORDOVA project underneath the Cordova project. That seems kind of mean. It's going to make a real mess out of version control. Personally I installed it in a sibling directory and then used `cordova plugin add` from there. But that's just me.

The current readme seems to be implying that the project's root (where its `config.xml` resides) is not version-controlled — only its `www` subdirectory is controlled, because the other directories contain a lot of autogenerated stuff that would better end in `.gitignore` anyway. In such setup it's fine to have a version-controlled `jxcore-cordova` as a mere sibling of a version-controlled `www`.

However, I agree that the current scheme of the plugin installation requires two steps (cloning, then installing) and that it might be simplified when Apache Cordova starts supporting the installation of plugins that are pulled directly from GitHub.

Apache Cordova plugins are currently [moving to npm registry](http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html).

Most developers of Node-based applications know that the `npm` command does support not only name-based installation (such as `npm install uue`) from the npm registry, but also URL-based installation (such as `npm install https://github.com/Mithgol/node-uue/tarball/master`) from GitHub.

I guess Apache Cordova's `cordova add plugin` should also support installing plugins from GitHub. You should probably make a feature request to its devs unless they have already figured it out.

**Comment by deefactorial** [comment]
You mean like this:

``` sh
cordova plugin add https://github.com/deefactorial/jxcore-cordova.git
```

**Comment by deefactorial** [comment]
[issued a PR](https://github.com/jxcore/jxcore-cordova/pull/22)

**Comment by Mithgol** [comment]
Yes, like this. Thanks for the PR.
