### ISSUE TITLE
Getting jxcore-cordova to work in Visual Studio 2015 RC environment

### ISSUE THREAD

**Issue by JimSEOW** [jxcore/jxcore-cordova#29]
I follow the steps and I manage to deploy to Genymotion and run the express sample.

I am attempting to develop using visual studio 2015 RC environment. It deploys but does not run in Genymotion. Error message window is illegal path. Has anyone attempted to develop in Visual studio 2015 RC?

Visual studo 2015RC provides an option to install custom plugin
using https://github.com/jxcore/jxcore-cordova.git, I am not able to install through visual studio.

I am still learning cordova and trying to figure out my way around.

**Comment by obastemur** [comment]
Actually It works as is.

What I did was ; (on VS2015)
- double click to config.xml
- Select Plugins
- Select 'git' and enter 'https://github.com/jxcore/jxcore-cordova'
- click Add

Screenshot
![ss-vs2015-jxcore](https://cloud.githubusercontent.com/assets/4390745/7843068/8e5c30b6-04a7-11e5-87d5-164e807919bc.jpg)

**Comment by JimSEOW** [comment]
The custom plugin install works!  However, after deploying the express sample to Genymotion (which works), VS reports there is error and it clashes the visual studio. Somethings has to do with illegal path. (a message window) I am not experienced to diagnose the problem, any suggestion? it could be due to Visual Studio 2015 RC instability - not sure.

**Comment by obastemur** [comment]
@Davtomas I've just tested with latest Win10 and it works. Actually I really liked the new simulator interface on VS2015. Closing this issue for now. Feel free to open it up if you see it's a jxcore issue.

**Comment by ktrzeciaknubisa** [comment]
Actually right now, since we keep binaries inside jx package (not in jxcore-cordova repo) the steps to install the plugin in VS 2015 would be slightly different. The idea is to download jxcore-codova plugin as jx package. e.g. [io.jxcore.node.jx](http://jxcordova.cloudapp.net/0.0.8/io.jxcore.node.jx), unpack it and then add as **Local** plugin instead if **Git**. 

The readme file has been updated for this: https://github.com/jxcore/jxcore-cordova#visual-studio
