### ISSUE TITLE
 cordova.fireWindowEvent event in PouchDB fails

### ISSUE THREAD

**Issue by sreesharp** [jxcore/jxcore-cordova#41]
When I use PouchDB and Express-PouchDB with JxCore-Cordova app, I get failure here in PouchDB code https://github.com/pouchdb/pouchdb/blob/master/lib/constructor.js#L148. 

Hey @yaronyg This is the root cause for 'pouch is undefined' error.

**Comment by yaronyg** [comment]
@obastemur what's happening is that PouchDB detects if it is running in a Cordova webview by looking to see if there is a global variable called 'cordova' (or phonegap, see [here](https://github.com/pouchdb/pouchdb/blob/3a8e0541af8a22cffd71fe9cda9800d3f1b583e4/lib/utils.js#L106) for the exact code). So having a global variable in JXCore called 'cordova' is bad.

So it looks like not only do we need registerToNative moved over to jxmobile or whatever the new name is, but we will need all the functions on the cordova object moved over. Otherwise we are going to keep blowing up when we use libraries like PouchDB that detect if they are running in a cordova webview by looking for the cordova global variable name.

Thanks!

**Comment by obastemur** [comment]
https://github.com/jxcore/jxcore-cordova/commit/714a6724a1ec30390aa7d3bbd3a2cfe6542502a4 fixes this issue (all 'cordova' needs to be 'Mobile')
