### ISSUE TITLE
<script type="text/javascript" charset="utf-8" src="jxcore.js"></script> Is not loading correctly

### ISSUE THREAD

**Issue by dortamiguel** [jxcore/jxcore-cordova#88]
It seems like jxcore.js is not accesible on iOS or android from index.html,

On iOS I get the following message:

Failed to load resource: The requested URL was not found on this server.

**Comment by ktrzeciaknubisa** [comment]
Which cordova cli version are you using?

**Comment by dortamiguel** [comment]
Cordova 5.3.3

**Comment by ktrzeciaknubisa** [comment]
And I guess it's on Android 6 device, right?

**Comment by dortamiguel** [comment]
I get this error on android and iOS. On android 6.0 appeared but I downgraded my phone to android 5.5.1. Now jxcore works except I keep getting the error of this issue tittle.

This is an screenshot that maybe can help you. (Android 5.5.1 nexus 5)

![screen shot 2015-10-25 at 15 11 30](https://cloud.githubusercontent.com/assets/3449006/10716274/0ed42920-7b2b-11e5-8749-cbe28a4f27cb.png)

**Comment by ktrzeciaknubisa** [comment]
[jxcore-cordova-release 0.0.8](https://github.com/jxcore/jxcore-cordova-release/tree/master/0.0.8) ? I confirm.

**Comment by dortamiguel** [comment]
Yes, I also tried 0.0.7 and I get the same result. Everything goes fine if I copy and load jxcore.js from other location.

**Comment by ktrzeciaknubisa** [comment]
Well, with 0.0.7 I saw your previous problem https://github.com/jxcore/jxcore-cordova/issues/87.

**Comment by dortamiguel** [comment]
Do you also get the same error?

**Comment by ktrzeciaknubisa** [comment]
Same error, however only on **Android 6** (AVD) and never on iOS 9 so far (simulator). Also I think #87 is related because they both happen for me at the same time:

> 10-25 20:28:30.164: E/AndroidProtocolHandler(3260): Unable to open asset URL: file:///android_asset/www/jxcore.js
> 10-25 20:28:31.532: E/jxcore(3260): Error!: ENOENT, no such file or directory '/data/data/com.example.hello/files/www'

**Comment by dortamiguel** [comment]
On iOS 9 when I reload the from the safari simulator inspector I get the same error, but also the app stops working.

![screen shot 2015-10-26 at 10 47 25](https://cloud.githubusercontent.com/assets/3449006/10727099/1e861a6e-7bcf-11e5-8def-4c777969b38e.png)

**Comment by ktrzeciaknubisa** [comment]
Looks like we have it sorted out. In the end those were two different problems.
1. `no such file or directory '/data/data/com.example.hello/files/www'` from #87 was stopping the app and coming to the screen as an alert. It is resolved now with a94bb7f3c460bd3f80da75bb7b52754068583472 - we'll publish the updated binary package soon.
2. `Unable to open asset URL: file:///android_asset/www/jxcore.js` is showing occasionally on regular app run on device, or each time when you reload by chrome/safari inspector. But it doesn't stop the app. The error comes from:
   
   ``` js
   <script type="text/javascript" charset="utf-8" src="jxcore.js"></script>
   ```
   
   because it looks like this line not even needed in `index.html`! I'm removing it and I'm able to run the app successfully! I guess that's because `cordova.js` loads `cordova_plugins.js` which in turn loads `jxcore.js`. 
   
   @obastemur I say we can remove it from our samples, too. What do you think?

**Comment by obastemur** [comment]
Sure

**Comment by ktrzeciaknubisa** [comment]
@ellipticaldoor This should work now. Please update jxcore-cordova release binaries (same version 0.0.8). If you're using [jxc](https://github.com/jxcore/jxc) you may type:

``` bash
$ jxc install --force-download
```

to get the latest update.
